tasks:
  - init: npm install
    command: npm start

vscode:
  extensions:
    - esbenp.prettier-vscode@5.1.3:t532ajsImUSrA9N8Bd7jQw==

ports:
  - name: Tiny Tapeout Flasher App
    port: 5173
    onOpen: open-preview
